function data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PART1A1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  PART1A1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  part1a1 = importfile("/Users/user/Documents/semester_b/lab/מגנטיות/week1/part1/a/part1_a_20_300.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-May-2022 17:06:47

%% Input handling

% If dataLines is not specified, define defaults

table = readtable(filename);

%% Set up the Import Options and import the data

% Import the data


data = struct();
keys = fieldnames(table);

for i = 1:length(keys)
    key = keys{i}
    name = filterKeyNames(key)
    if name ~= NaN
        data.(name) = table.(key)
end

end
