function [fitresultIn, fitresultOut, gofIn, gofOut] = createFit(data, name)
%CREATEFIT(R1508_T,R1508_V)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : R1508_t
%      Y Output: R1508_v
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Apr-2022 16:16:54


%% Fit: 'untitled fit 2'.
% [t, v] = cleanValues(t,v);
[tIn, vIn] = prepareCurveData( data.tIn, data.vIn);
[ tOut, vOut] =  prepareCurveData(data.tOut, data.vOut);


% Fit model to data.
[fitresultIn, gofIn] = oneFit(tIn, vIn, name);
[fitresultOut, gofOut] = oneFit(tOut, vOut, name);


% Plot fit with data.
fig = figure( 'Name', 'untitled fit 2' );
plotIn = plot( fitresultIn, tIn, vIn);
hold on
plotOut = plot( fitresultOut, tOut, vOut);
set(plotIn,'color','blue');

% Label axes
xlabel( 'Voltage (Volt)', 'Interpreter', 'none' );
ylabel( 'Time (s)', 'Interpreter', 'none' );
title( sprintf('Votage as Function of Time %s hz', name));
legend([sprintf("r^2 in: %f",gofIn.rsquare), sprintf("r^2 out: %f",gofOut.rsquare), ...
sprintf("In properties: %s", displayFitProperties(fitresultIn)), sprintf("Out properties: %s", displayFitProperties(fitresultOut))]);
% text(0,0, string(optsOut.StartPoint));
grid on

saveas(fig, sprintf("png/%s.png", name), "png");
saveas(fig, sprintf("fig/%s.fig", name), "fig");

end


