function [fitresult, gof] = createFit(volt, amper,verr,Ierr)
%CREATEFIT(VOLT,AMPER)
%  Create a fit.
%
%  Data for 'linear fitting (a*x+b)' fit:
%      X Input : volt
%      Y Output: amper
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Apr-2022 13:25:27


%% Fit: 'linear fitting (a*x+b)'.
[xData, yData] = prepareCurveData( volt, amper );

% Set up fittype and options.
ft = fittype( 'poly1' );
excludedPoints = excludedata( xData, yData, 'Indices', 1 );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'linear fitting (a*x+b)' );
errorbar( xData, yData,Ierr,Ierr,verr,verr,"LineStyle","none");
hold on
% h = plot( fitresult, [0;xData], [0;yData], excludedPoints );

excludedPoints = excludedata( [-0.2;xData], [fitresult(-0.2);yData], 'Indices', 2 );
h = plot( fitresult, [-0.2;xData], [fitresult(-0.2);yData], excludedPoints );
legend( h, 'amper vs. volt', 'Excluded amper vs. volt', 'linear fitting (a*x+b)', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'voltage [Volt]', 'Interpreter', 'none','FontSize', 20);
ylabel( 'current [Amper]', 'Interpreter', 'none', 'FontSize', 20);
title('current as function of voltage', 'FontSize', 25)
set(gca,'FontSize',20)
grid on


