function week2part1R2433k = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  WEEK2PART1R2433K = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  WEEK2PART1R2433K = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  week2part1R2433k = importfile1("/Users/user/Documents/MATLAB/circles/week2/week_2_part_1_R2433k.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Apr-2022 19:48:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "E6", "VarName5", "Var6", "Var7", "Var8", "Var9", "E1", "VarName11"];
opts.SelectedVariableNames = ["E6", "VarName5", "E1", "VarName11"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "string", "string", "string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var6", "Var7", "Var8", "Var9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var6", "Var7", "Var8", "Var9"], "EmptyFieldRule", "auto");

% Import the data
week2part1R2433k = readtable(filename, opts);

end